apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/products:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: demo
spec:
  selector:
    app: products
  ports:
    - port: 80
      targetPort: 3002
