apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/users:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: demo
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer